import './globals.css'
import type { Metadata } from 'next'
//import { Noto_Sans_JP } from 'next/font/google'
import { DotGothic16 } from 'next/font/google'

const Dot_Gothic_16 = DotGothic16({
  weight: ["400"],
  preload: false,
 })

// 1. フォントの読み込み
/*
const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});
*/

export const metadata: Metadata = {
  title: 'Next.js 13',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="ja">
      <body className={Dot_Gothic_16.className}>{children}</body>
    </html>
  )
}
